version: "3"

services:
    web:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/usr/share/nginx/html
            - ./site.conf:etc/nginx/conf.d/site.conf
    # php:
    #     image: php:7-fpm