version: "2"

services:
    web:
        image: nginx:latest
        container_name: web
        ports:
            - "8000:80"
        volumes:
            - ./src:/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - server-network
    php:
        image: php:fpm
        container_name: php
        volumes:
            - ./src:/src
        networks:
            - server-network

networks:
    server-network:
        driver: bridge
